//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AInBox.Queue.WebService.Console.NotificationService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://notifications.ainbox.com.br/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseResultModel))]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SendEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddEnterpriseToDatabaseOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddModuleToDatabaseOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::AInBox.Queue.WebService.Console.Properties.Settings.Default.AInBox_Queue_WebService_Console_NotificationService_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendEmailCompletedEventHandler SendEmailCompleted;
        
        /// <remarks/>
        public event AddEnterpriseToDatabaseCompletedEventHandler AddEnterpriseToDatabaseCompleted;
        
        /// <remarks/>
        public event AddModuleToDatabaseCompletedEventHandler AddModuleToDatabaseCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://notifications.ainbox.com.br/SendEmail", RequestNamespace="http://notifications.ainbox.com.br/", ResponseNamespace="http://notifications.ainbox.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SendEmailResult SendEmail(SendEmailBinding model) {
            object[] results = this.Invoke("SendEmail", new object[] {
                        model});
            return ((SendEmailResult)(results[0]));
        }
        
        /// <remarks/>
        public void SendEmailAsync(SendEmailBinding model) {
            this.SendEmailAsync(model, null);
        }
        
        /// <remarks/>
        public void SendEmailAsync(SendEmailBinding model, object userState) {
            if ((this.SendEmailOperationCompleted == null)) {
                this.SendEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendEmailOperationCompleted);
            }
            this.InvokeAsync("SendEmail", new object[] {
                        model}, this.SendEmailOperationCompleted, userState);
        }
        
        private void OnSendEmailOperationCompleted(object arg) {
            if ((this.SendEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendEmailCompleted(this, new SendEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://notifications.ainbox.com.br/AddEnterpriseToDatabase", RequestNamespace="http://notifications.ainbox.com.br/", ResponseNamespace="http://notifications.ainbox.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AddEnterpriseToDatabaseResult AddEnterpriseToDatabase(AddEnterpriseToDatabaseBinding model) {
            object[] results = this.Invoke("AddEnterpriseToDatabase", new object[] {
                        model});
            return ((AddEnterpriseToDatabaseResult)(results[0]));
        }
        
        /// <remarks/>
        public void AddEnterpriseToDatabaseAsync(AddEnterpriseToDatabaseBinding model) {
            this.AddEnterpriseToDatabaseAsync(model, null);
        }
        
        /// <remarks/>
        public void AddEnterpriseToDatabaseAsync(AddEnterpriseToDatabaseBinding model, object userState) {
            if ((this.AddEnterpriseToDatabaseOperationCompleted == null)) {
                this.AddEnterpriseToDatabaseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddEnterpriseToDatabaseOperationCompleted);
            }
            this.InvokeAsync("AddEnterpriseToDatabase", new object[] {
                        model}, this.AddEnterpriseToDatabaseOperationCompleted, userState);
        }
        
        private void OnAddEnterpriseToDatabaseOperationCompleted(object arg) {
            if ((this.AddEnterpriseToDatabaseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddEnterpriseToDatabaseCompleted(this, new AddEnterpriseToDatabaseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://notifications.ainbox.com.br/AddModuleToDatabase", RequestNamespace="http://notifications.ainbox.com.br/", ResponseNamespace="http://notifications.ainbox.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AddModuleToDatabaseResult AddModuleToDatabase(AddModuleToDatabaseBinding model) {
            object[] results = this.Invoke("AddModuleToDatabase", new object[] {
                        model});
            return ((AddModuleToDatabaseResult)(results[0]));
        }
        
        /// <remarks/>
        public void AddModuleToDatabaseAsync(AddModuleToDatabaseBinding model) {
            this.AddModuleToDatabaseAsync(model, null);
        }
        
        /// <remarks/>
        public void AddModuleToDatabaseAsync(AddModuleToDatabaseBinding model, object userState) {
            if ((this.AddModuleToDatabaseOperationCompleted == null)) {
                this.AddModuleToDatabaseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddModuleToDatabaseOperationCompleted);
            }
            this.InvokeAsync("AddModuleToDatabase", new object[] {
                        model}, this.AddModuleToDatabaseOperationCompleted, userState);
        }
        
        private void OnAddModuleToDatabaseOperationCompleted(object arg) {
            if ((this.AddModuleToDatabaseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddModuleToDatabaseCompleted(this, new AddModuleToDatabaseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://notifications.ainbox.com.br/")]
    public partial class SendEmailBinding {
        
        private int moduleIdField;
        
        private string referenceNameField;
        
        private int referenceIdField;
        
        private string referenceParametersField;
        
        private System.Nullable<System.DateTime> scheduleDateField;
        
        private int priorityField;
        
        private string toField;
        
        private string ccField;
        
        private string bccField;
        
        private string subjectField;
        
        private string bodyField;
        
        private string bodyTextField;
        
        private string subjectEncodingField;
        
        private string bodyEncodingField;
        
        private bool isBodyHtmlField;
        
        /// <remarks/>
        public int ModuleId {
            get {
                return this.moduleIdField;
            }
            set {
                this.moduleIdField = value;
            }
        }
        
        /// <remarks/>
        public string ReferenceName {
            get {
                return this.referenceNameField;
            }
            set {
                this.referenceNameField = value;
            }
        }
        
        /// <remarks/>
        public int ReferenceId {
            get {
                return this.referenceIdField;
            }
            set {
                this.referenceIdField = value;
            }
        }
        
        /// <remarks/>
        public string ReferenceParameters {
            get {
                return this.referenceParametersField;
            }
            set {
                this.referenceParametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ScheduleDate {
            get {
                return this.scheduleDateField;
            }
            set {
                this.scheduleDateField = value;
            }
        }
        
        /// <remarks/>
        public int Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        public string To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        public string CC {
            get {
                return this.ccField;
            }
            set {
                this.ccField = value;
            }
        }
        
        /// <remarks/>
        public string Bcc {
            get {
                return this.bccField;
            }
            set {
                this.bccField = value;
            }
        }
        
        /// <remarks/>
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        public string Body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
        
        /// <remarks/>
        public string BodyText {
            get {
                return this.bodyTextField;
            }
            set {
                this.bodyTextField = value;
            }
        }
        
        /// <remarks/>
        public string SubjectEncoding {
            get {
                return this.subjectEncodingField;
            }
            set {
                this.subjectEncodingField = value;
            }
        }
        
        /// <remarks/>
        public string BodyEncoding {
            get {
                return this.bodyEncodingField;
            }
            set {
                this.bodyEncodingField = value;
            }
        }
        
        /// <remarks/>
        public bool IsBodyHtml {
            get {
                return this.isBodyHtmlField;
            }
            set {
                this.isBodyHtmlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://notifications.ainbox.com.br/")]
    public partial class AddModuleToDatabaseBinding {
        
        private int enterpriseIdField;
        
        private string nameField;
        
        private string fromNameField;
        
        private string fromEmailField;
        
        private string restrictIpsField;
        
        private bool activeField;
        
        /// <remarks/>
        public int EnterpriseId {
            get {
                return this.enterpriseIdField;
            }
            set {
                this.enterpriseIdField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string FromName {
            get {
                return this.fromNameField;
            }
            set {
                this.fromNameField = value;
            }
        }
        
        /// <remarks/>
        public string FromEmail {
            get {
                return this.fromEmailField;
            }
            set {
                this.fromEmailField = value;
            }
        }
        
        /// <remarks/>
        public string RestrictIps {
            get {
                return this.restrictIpsField;
            }
            set {
                this.restrictIpsField = value;
            }
        }
        
        /// <remarks/>
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://notifications.ainbox.com.br/")]
    public partial class AddEnterpriseToDatabaseBinding {
        
        private string nameField;
        
        private string usernameField;
        
        private string passwordField;
        
        private string fromNameField;
        
        private string fromEmailField;
        
        private string hostField;
        
        private System.Nullable<int> portField;
        
        private string serverUsernameField;
        
        private string serverPasswordField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string FromName {
            get {
                return this.fromNameField;
            }
            set {
                this.fromNameField = value;
            }
        }
        
        /// <remarks/>
        public string FromEmail {
            get {
                return this.fromEmailField;
            }
            set {
                this.fromEmailField = value;
            }
        }
        
        /// <remarks/>
        public string Host {
            get {
                return this.hostField;
            }
            set {
                this.hostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Port {
            get {
                return this.portField;
            }
            set {
                this.portField = value;
            }
        }
        
        /// <remarks/>
        public string ServerUsername {
            get {
                return this.serverUsernameField;
            }
            set {
                this.serverUsernameField = value;
            }
        }
        
        /// <remarks/>
        public string ServerPassword {
            get {
                return this.serverPasswordField;
            }
            set {
                this.serverPasswordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AddModuleToDatabaseResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AddEnterpriseToDatabaseResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SendEmailResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://notifications.ainbox.com.br/")]
    public partial class BaseResultModel {
        
        private bool isValidField;
        
        private string messageField;
        
        /// <remarks/>
        public bool IsValid {
            get {
                return this.isValidField;
            }
            set {
                this.isValidField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://notifications.ainbox.com.br/")]
    public partial class AddModuleToDatabaseResult : BaseResultModel {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://notifications.ainbox.com.br/")]
    public partial class AddEnterpriseToDatabaseResult : BaseResultModel {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://notifications.ainbox.com.br/")]
    public partial class SendEmailResult : BaseResultModel {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SendEmailCompletedEventHandler(object sender, SendEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SendEmailResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SendEmailResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void AddEnterpriseToDatabaseCompletedEventHandler(object sender, AddEnterpriseToDatabaseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddEnterpriseToDatabaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddEnterpriseToDatabaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AddEnterpriseToDatabaseResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AddEnterpriseToDatabaseResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void AddModuleToDatabaseCompletedEventHandler(object sender, AddModuleToDatabaseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddModuleToDatabaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddModuleToDatabaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AddModuleToDatabaseResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AddModuleToDatabaseResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591